dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "3.6"
env:
  -DJANGO=2.2.3

before_install:
  - export DJANGO_SECRET_KEY='2oejofSDFOIQefjei2379#&#'
  - export PYTHONPATH=$HOME/builds/tonypnode/portfolio_site

install:
  - pip install -r requirements.txt

script:
  - python manage.py test