language: python
python:
  - "3.7"
env:
  -DJANGO=2.2.2

before_install:
  - export DJANGO_SECRET_KEY='2oejofSDFOIQefjei2379#&#'
  - export PYTHONPATH=$HOME/builds/tonypnode/portfolio_site
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt


script:
  - python manage.py test