dist: xenial   # required for Python >= 3.7
anguage: python
python:
  - "3.7"
  - "3.6"
env:
  -DJANGO=2.2.2

before_install:
  - export DJANGO_SECRET_KEY='2oejofSDFOIQefjei2379#&#'
  - export PYTHONPATH=$HOME/builds/tonypnode/portfolio_site
  -
install:
  - pip3 install -r requirements.txt


script:
  - python3 manage.py test